repos:
    - repo: local
      hooks:
          - id: black
            name: "format code with black"
            entry: black
            language: system
            types:
                - python
            args:
                - --skip-string-normalization
          - id: isort
            name: "format imports with isort"
            entry: isort
            language: system
            types:
                - python
          - id: flake8
            name: "lint code with flake8"
            entry: flake8
            language: system
            types:
                - python
          - id: bandit
            name: "check security"
            entry: bandit
            language: system
            args:
                - --quiet
                - --exclude=__tests__
            types:
                - python
default_stages:
    - commit
